codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 80%
        paths:
          - 'src/'
    patch:
      default:
        target: auto
        threshold: 80%
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
