# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test --workspace=packages/libraries/filter -- --coverage

      - name: List coverage directory
        run: ls -la ./packages/libraries/filter/coverage/

      - name: Check if lcov.info exists
        run: |
          if [ -f "./packages/libraries/filter/coverage/lcov.info" ]; then
            echo "lcov.info found"
            cat ./packages/libraries/filter/coverage/lcov.info | head -10
          else
            echo "lcov.info not found"
            ls -la ./packages/libraries/filter/coverage/
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/libraries/filter/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
